name: 'SQLEco'
version: ${projectVersion}
author: 'DevCyntrix'
description: 'A vault economy implementation using mariadb/mysql'
main: 'de.devcyntrix.sqleco.SQLEcoPlugin'
api-version: 1.20
depend:
  - Vault